apiVersion: v1
kind: Service
metadata:
  name: website-prt-org
  labels:
    app: website-prt-org
spec:
  type: NodePort
  ports:
  - port: 30010
    targetPort: 80
    protocol: TCP
  selector:
    app: website-prt-org
