apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-prt-org
spec:
  replicas: 5
  selector:
    matchLabels:
      app: website-prt-org
  template:
    metadata:
      labels:
        app: website-prt-org
    spec:
      containers:
      - name: website-prt-org
        image: chitrad/website-prt-org:laatest
        ports:
        - containerPort: 80
